version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - {PORT}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user
      MYSQL_TCP_PORT: 3307
    volumes:
      - INIT_DB_PATH:/docker-entrypoint-initdb.d/docker_init.sql
      - DUMP_PATH:/mysql_dump.sql
      - RESTORE_PATH:/docker-entrypoint-initdb.d/mysql_restore.sh
