version: '3'
services:
  postgres:
    image: 'postgres:14.0'
    ports:
      - {PORT}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_user
    volumes:
      - INIT_DB_PATH:/docker-entrypoint-initdb.d/docker_init.sql
      - DUMP_PATH:/pg_dump.sql
      - RESTORE_PATH:/docker-entrypoint-initdb.d/pg_restore.sh
